
name: Version Release Check

on:
  release:
    types: [published]
  workflow_call:
    inputs:
      release-tag:
        required: true
        type: string

env:
  RUST_BACKTRACE: 1
  SHELL: /bin/bash
  CARGO_INCREMENTAL: 0

jobs:
  release-tag:
    runs-on: ubuntu-latest
    steps:
      - id: tag-name
        run: |
          if [[ '${{ inputs.release-tag }}' != '' ]]; then
            echo "RELEASE_TAG=${{ inputs.release-tag }}" >> ${GITHUB_OUTPUT}
          elif [[ '${{ github.event_name }}' == 'release' ]]; then
            echo "RELEASE_TAG=${{ github.ref_name }}" >> ${GITHUB_OUTPUT}
          fi
    outputs:
      release-tag: ${{ steps.tag-name.outputs.RELEASE_TAG }}

  verify-artifact:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { target: aarch64-apple-darwin, os: macos-14 }
          - { target: x86_64-apple-darwin, os: macos-13 }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest }
          - { target: x86_64-pc-windows-msvc, os: windows-latest }
    runs-on: ${{ matrix.platform.os }}
    needs: release-tag
    env:
      MOZJS_ARCHIVE: libmozjs-${{ matrix.platform.target }}.tar.gz
    steps:
      - uses: actions/checkout@v4
      - name: Download prebuilt mozjs from artifact
        if: ${{ needs.release-tag.outputs.release-tag == '' }}
        uses: actions/download-artifact@v4
        with:
          name: libmozjs-${{ matrix.platform.target }}.tar.gz
      - name: Download prebuilt mozjs from release
        if: ${{ needs.release-tag.outputs.release-tag != '' }}
        run: |
          curl -L https://github.com/${{ github.repository_owner }}/mozjs/releases/download/${{ needs.release-tag.outputs.release-tag }}/libmozjs-${{ matrix.platform.target }}.tar.gz
      - name: Display structure of downloaded files
        run: ls -R
      - name: Build
        run: |
          cargo build --verbose --features streams
          cargo test --tests --examples --verbose ${{ matrix.features }}
