name: Rust

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  merge_group:
    types: [checks_requested]
  schedule:
    # Runs at 03:30, every Saturday
    - cron: "30 3 * * 6"

env:
  RUST_BACKTRACE: 1
  SHELL: /bin/bash
  CARGO_INCREMENTAL: 0
  MOZJS_CREATE_MIRROR: 1

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        features: ["--features debugmozjs", ""]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install deps
        run: |
          sudo apt install llvm -y
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Build
        run: |
          cargo build --verbose ${{ matrix.features }}
          cargo test --tests --examples --verbose ${{ matrix.features }}
      - name: Check wrappers integrity
        # we generate wrappers only without debugmozjs
        if: ${{ matrix.features == '' }}
        run: |
          bash ./mozjs/src/generate_wrappers.sh
          git diff --quiet --exit-code
  integrity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Check formatting
        run: cargo fmt --check
      - name: Get mozjs
        run: |
          bash ./mozjs-sys/etc/get_mozjs.sh
      - name: Apply patch
        run: |
          python3 ./mozjs-sys/etc/update.py --no-commit mozjs.tar.xz
          # Run `git add` here to force CRLF converted into LF
          # so that we can check diff properly in next run
          git add --all mozjs
      - name: Check patch integrity
        working-directory: ./mozjs-sys
        # Because we've added files in previous run, we need to
        # check diff with `--staged`.
        run: |
          git diff --staged --no-ext-diff --quiet --exit-code

  build_result:
    name: Result
    runs-on: ubuntu-latest
    needs:
      ["linux", "integrity"]
    if: ${{ always() }}
    steps:
      - name: Mark the job as successful
        if: ${{ !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
        run: exit 0
      - name: Mark the job as unsuccessful
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
